export const ADMIN_USER_REQUEST = "ADMIN_USER_REQUEST"
export const ADMIN_USER_SUCCESS = "ADMIN_USER_SUCCESS"
export const ADMIN_USER_FAIL = "ADMIN_USER_FAIL"
export const ADMIN_USER_CLEAR= "ADMIN_USER_CLEAR"

export const ADMIN_GET_USER_DETAIL_REQUEST= "ADMIN_GET_USER_DETAIL_REQUEST"
export const ADMIN_GET_USER_DETAIL_SUCCESS= "ADMIN_GET_USER_DETAIL_SUCCESS"
export const ADMIN_GET_USER_DETAIL_FAIL = "ADMIN_GET_USER_DETAIL_FAIL"
export const ADMIN_GET_USER_CLEAR = "ADMIN_GET_USER_CLEAR"

export const ADMIN_EDIT_USER_REQUEST = "ADMIN_EDIT_USER_REQUEST"
export const ADMIN_EDIT_USER_SUCCESS = "ADMIN_EDIT_USER_SUCCESS"
export const ADMIN_EDIT_USER_FAIL = "ADMIN_EDIT_USER_FAIL"
export const ADMIN_EDIT_USER_CLEAR = "ADMIN_EDIT_USER_CLEAR"

export const ADMIN_DELETE_USER_REQUEST = "ADMIN_DELETE_USER_REQUEST"
export const ADMIN_DELETE_USER_SUCCESS = "ADMIN_DELETE_USER_SUCCESS"
export const ADMIN_DELETE_USER_FAIL = "ADMIN_DELETE_USER_FAIL"

export const ADMIN_GET_PRODUCT_REQUEST = "ADMIN_GET_PRODUCT_REQUEST"
export const ADMIN_GET_PRODUCT_SUCCESS = "ADMIN_GET_PRODUCT_SUCCESS"
export const ADMIN_GET_PRODUCT_FAIL = "ADMIN_GET_PRODUCT_FAIL"
export const ADMIN_GET_PRODUCT_CLEAR = "ADMIN_GET_PRODUCT_CLEAR"

export const ADMIN_GET_PRODUCT_DETAIL_REQUEST = "ADMIN_GET_PRODUCT_DETAIL_REQUEST"
export const ADMIN_GET_PRODUCT_DETAIL_SUCCESS = "ADMIN_GET_PRODUCT_DETAIL_SUCCESS"
export const ADMIN_GET_PRODUCT_DETAIL_FAIL = "ADMIN_GET_PRODUCT_DETAIL_FAIL"
export const ADMIN_GET_PRODUCT_DETAIL_CLEAR = "ADMIN_GET_PRODUCT_DETAIL_CLEAR"

export const ADMIN_ADD_PRODUCT_REQUEST = "ADMIN_ADD_PRODUCT_REQUEST"
export const ADMIN_ADD_PRODUCT_SUCCESS = "ADMIN_ADD_PRODUCT_SUCCESS"
export const ADMIN_ADD_PRODUCT_FAIL = "ADMIN_ADD_PRODUCT_FAIL"
export const ADMIN_ADD_PRODUCT_CLEAR= "ADMIN_ADD_PRODUCT_CLEAR"

export const ADMIN_EDIT_PRODUCT_REQUEST = "ADMIN_EDIT_PRODUCT_REQUEST"
export const ADMIN_EDIT_PRODUCT_SUCCESS = "ADMIN_EDIT_PRODUCT_SUCCESS"
export const ADMIN_EDIT_PRODUCT_FAIL = "ADMIN_EDIT_PRODUCT_FAIL"
export const ADMIN_EDIT_PRODUCT_CLEAR = "ADMIN_EDIT_PRODUCT_CLEAR"

export const ADMIN_DELETE_PRODUCT_REQUEST = "ADMIN_DELETE_PRODUCT_REQUEST"
export const ADMIN_DELETE_PRODUCT_SUCCESS = "ADMIN_DELETE_PRODUCT_SUCCESS"
export const ADMIN_DELETE_PRODUCT_FAIL = "ADMIN_DELETE_PRODUCT_FAIL"

export const ADMIN_ORDER_REQUEST = "ADMIN_ORDER_REQUEST"
export const ADMIN_ORDER_SUCCESS = "ADMIN_ORDER_SUCCESS"
export const ADMIN_ORDER_FAIL = "ADMIN_ORDER_FAIL"

export const ADMIN_MARK_DELIVERED_REQUEST= "ADMIN_MARK_DELIVERED_REQUEST"
export const ADMIN_MARK_DELIVERED_SUCCESS= "ADMIN_MARK_DELIVERED_SUCCESS"
export const ADMIN_MARK_DELIVERED_FAIL= "ADMIN_MARK_DELIVERED_FAIL"

export const ADMIN_SEARCH_USER_REQUEST= "ADMIN_SEARCH_USER_REQUEST"
export const ADMIN_SEARCH_USER_SUCCESS= "ADMIN_SEARCH_USER_SUCCESS"
export const ADMIN_SEARCH_USER_FAIL= "ADMIN_SEARCH_USER_FAIL"