export const AUTH_SIGN_UP_REQUEST= "AUTH_SIGN_UP_REQUEST"
export const AUTH_SIGN_UP_SUCCESS= "AUTH_SIGN_UP_SUCCESS"
export const AUTH_SIGN_UP_FAIL= "AUTH_SIGN_UP_FAIL"

export const AUTH_SIGN_IN_REQUEST= "AUTH_SIGN_IN_REQUEST"
export const AUTH_SIGN_IN_SUCCESS= "AUTH_SIGN_IN_SUCCESS"
export const AUTH_SIGN_IN_FAIL= "AUTH_SIGN_IN_FAIL"

export const AUTH_SIGN_OUT_REQUEST= "AUTH_SIGN_OUT_REQUEST"
export const AUTH_SIGN_OUT_SUCCESS= "AUTH_SIGN_OUT_SUCCESS"
export const AUTH_SIGN_OUT_FAIL= "AUTH_SIGN_OUT_FAIL"

export const GET_AUTH_USER_REQUEST= "GET_AUTH_USER_REQUEST"
export const GET_AUTH_USER_SUCCESS= "GET_AUTH_USER_SUCCESS"
export const GET_AUTH_USER_FAIL= "GET_AUTH_USER_FAIL"

export const UPDATE_PROFILE_REQUEST= "UPDATE_PROFILE_REQUEST"
export const UPDATE_PROFILE_SUCCESS= "UPDATE_PROFILE_SUCCESS"
export const UPDATE_PROFILE_FAIL= "UPDATE_PROFILE_FAIL"
export const UPDATE_PROFILE_CLEAR= "UPDATE_PROFILE_CLEAR"

export const FORGET_PASSWORD_REQUEST= "FORGET_PASSWORD_REQUEST"
export const FORGET_PASSWORD_SUCCESS= "FORGET_PASSWORD_SUCCESS"
export const FORGET_PASSWORD_FAIL= "FORGET_PASSWORD_FAIL"
export const FORGET_PASSWORD_CLEAR= "FORGET_PASSWORD_CLEAR"

export const GET_USER_ORDER_REQUEST= "GET_USER_ORDER_REQUEST"
export const GET_USER_ORDER_SUCCESS= "GET_USER_ORDER_SUCCESS"
export const GET_USER_ORDER_FAIL= "GET_USER_ORDER_FAIL"