export const ADD_TO_CART_REQUEST= "ADD_TO_CART_REQUEST"
export const ADD_TO_CART_SUCCESS= "ADD_TO_CART_SUCCESS"
export const ADD_TO_CART_FAIL ="ADD_TO_CART_FAIL"
export const GET_CART_SUCCESS = "GET_CART_SUCCESS"
export const LEFT_TO_CART_CLEAR= "LEFT_TO_CART_CLEAR"

export const EDIT_TO_CART_REQUEST= "EDIT_TO_CART_REQUEST"
export const EDIT_TO_CART_SUCCESS= "EDIT_TO_CART_SUCCESS"
export const EDIT_TO_CART_FAIL= "EDIT_TO_CART_FAIL"

export const DELETE_TO_CART_REQUEST= "DELETE_TO_CART_REQUEST"
export const DELETE_TO_CART_SUCCESS="DELETE_TO_CART_SUCCESS"
export const DELETE_TO_CART_FAIL= "DELETE_TO_CART_FAIL"

export const ADD_SHIPPING_REQUEST= "ADD_SHIPPING_REQUEST"
export const ADD_SHIPPING_SUCCESS= "ADD_SHIPPING_SUCCESS"
export const ADD_SHIPPING_FAIL= "ADD_SHIPPING_FAIL"

export const ADD_PAYMENT_REQUEST= "ADD_PAYMENT_REQUEST"
export const ADD_PAYMENT_SUCCESS= "ADD_PAYMENT_SUCCESS"
export const ADD_PAYMENT_FAIL= "ADD_PAYMENT_FAIL"

export const PlACE_ORDER_REQUEST= "PlACE_ORDER_REQUEST"
export const PLACE_ORDER_SUCCESS= "PLACE_ORDER_SUCCESS"
export const PLACE_ORDER_FAIL= "PLACE_ORDER_FAIL"

export const GET_ORDER_DETAIL_REQUEST= "GET_ORDER_DETAIL_REQUEST"
export const GET_ORDER_DETAIL_SUCCESS= "GET_ORDER_DETAIL_SUCCESS"
export const GET_ORDER_DETAIL_FAIL= "GET_ORDER_DETAIL_FAIL"
export const GET_ORDER_DETAIL_CLEAR= "GET_ORDER_DETAIL_CLEAR"

export const PAID_ORDER_REQUEST= "PAID_ORDER_REQUEST"
export const PAID_ORDER_SUCCESS= "PAID_ORDER_SUCCESS"
export const PAID_ORDER_FAIL= "PAID_ORDER_FAIL"