export const GET_PRODUCT_LIST_REQUEST= "GET_PRODUCT_LIST_REQUEST"
export const GET_PRODUCT_LIST_SUCCESS= "GET_PRODUCT_LIST_SUCCESS"
export const GET_PRODUCT_LIST_FAIL= "GET_PRODUCT_LIST_FAIL"

export const GET_PRODUCT_SLIDE_REQUEST= "GET_PRODUCT_SLIDE_REQUEST"
export const GET_PRODUCT_SLIDE_SUCCESS= "GET_PRODUCT_SLIDE_SUCCESS"
export const GET_PRODUCT_SLIDE_FAIL= "GET_PRODUCT_SLIDE_FAIL"

export const GET_PRODUCT_DETAIL_REQUEST= "GET_PRODUCT_DETAIL_REQUEST"
export const GET_PRODUCT_DETAIL_SUCCESS= "GET_PRODUCT_DETAIL_SUCCESS"
export const GET_PRODUCT_DETAIL_FAIL= "GET_PRODUCT_DETAIL_FAIL"

export const POST_REVIEW_REQUEST= "POST_REVIEW_REQUEST"
export const POST_REVIEW_SUCCESS = "POST_REVIEW_SUCCESS"
export const POST_REVIEW_FAIL = "POST_REVIEW_FAIL"
export const POST_REVIEW_CLEAR= "POST_REVIEW_CLEAR"

export const SEARCH_PRODUCT_REQUEST= "SEARCH_PRODUCT_REQUEST"
export const SEARCH_PRODUCT_SUCCESS= "SEARCH_PRODUCT_SUCCESS"
export const SEARCH_PRODUCT_FAIL= "SEARCH_PRODUCT_FAIL"